version: '3'
services:
  dgt-backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DISCORD_REDIRECT_URL: ${DISCORD_REDIRECT_URL}
    restart: always


  db:
    image: postgres:17
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d dgt" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_DB: dgt
      POSTGRES_USER : root
      POSTGRES_PASSWORD : ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
