// Package success_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package success_api

import (
	"github.com/gin-gonic/gin"
)

// DungeonSuccess defines model for DungeonSuccess.
type DungeonSuccess struct {
	Dungeon string `json:"dungeon"`
	Level   int    `json:"level"`
	Name    string `json:"name"`
}

// DungeonSuccessMap defines model for DungeonSuccessMap.
type DungeonSuccessMap map[string]DungeonSuccess

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /success/dungeons)
	GetSuccessDungeons(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetSuccessDungeons operation middleware
func (siw *ServerInterfaceWrapper) GetSuccessDungeons(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSuccessDungeons(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/success/dungeons", wrapper.GetSuccessDungeons)
}
