openapi: 3.1.0
info:
  title: Dofus Guild Tracker
  description: Dofus Guild Tracker
  version: 0.1.0
servers:
  - url: 'https'
paths:
  # Monitoring Endpoint
  /ping:
    $ref: './monitoring/api.yaml#/paths/~1ping'
  # Auth Endpoint
  /login:
    $ref: './auth/api.yaml#/paths/~1login'
  /redirect:
    $ref: './auth/api.yaml#/paths/~1redirect'
  /refresh:
    $ref: './auth/api.yaml#/paths/~1refresh'
  /me:
    $ref: './auth/api.yaml#/paths/~1me'
  # Guild Enpoints
  /guilds:
    $ref: './guilds/api.yaml#/paths/~1guilds'