openapi: 3.0.0
info:
  title: Auth
  description: Auth
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /login:
    get:
      responses:
        '200':
          description: The login link to redirect the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /redirect:
    get:
      responses:
        '302':
          description: The redirect from discord that will redirect to the frontend and set the cookie access_token
          headers:
            Set-Cookie:
              schema:
                type: string
                example: access_token=abcde12345; Path=/; HttpOnly
        '500':
          description: Internal Error when calling discord
  /refresh:
    get:
      security:
        - basicAuth: [] # <-- use the same name here
      responses:
        '200':
          description: Return new access token as a cookie
          headers:
            Set-Cookie:
              schema:
                type: string
                example: access_token=abcde12345; Path=/; HttpOnly
  /me:
    get:
      security:
        - basicAuth: []
      responses:
        '200':
          description: Get current logged user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer
  schemas:
    LoginResponse:
      type: object
      required:
        - link
      properties:
        link:
          type: string
    UserInfo:
      type: object
      required:
        - username
        - avatar
      properties:
        username:
          type: string
        avatar:
          type: string
          example: https://cnd.discord.com/test.png
    Error:
      type: object
      properties:
        error:
          type: string


