openapi: 3.0.0
info:
  title: Characters
  description: Characters
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /characters:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CharacterInfo'
      security:
        - basicAuth: []
      responses:
        '201':
          description: Guild created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      description: Get the owned characters of the user
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Character owned by the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CharacterResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /characters/{id}:
    get:
      description: Get the character from it's id
      parameters:
        - name: id
          in: path
          schema:
            type: string
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Character requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Character not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Delete the character
      parameters:
        - name: id
          in: path
          schema:
            type: string
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Character deleted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Character doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Character not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /characters/{id}/success/{successID}:
    post:
      description: Add a success
      parameters:
        - name: id
          in: path
          schema:
            type: string
        - name: successID
          in: path
          schema:
            type: string
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Success added
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Character doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Character not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /characters/{id}/level/{level}:
    post:
      description: Change level of an user
      parameters:
        - name: id
          in: path
          schema:
            type: string
        - name: level
          in: path
          schema:
            type: number
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Success added
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Character doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Character not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /characters/{id}/success/dungeons:
    put:
      description: Replace Success
      parameters:
        - name: id
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string

      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Success added
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Character doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Character not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /characters/success/dungeons/{dungeonID}/search:
    get:
      description: Get Character that are missing success of a dungeon
      parameters:
        - name: dungeonID
          in: path
          schema:
            type: string
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Search done
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer
  schemas:
    CharacterInfo:
      type: object
      required:
        - name
        - server
        - class
        - level
        - guild_code
      properties:
        name:
          type: string
        server:
          type: string
        class:
          type: string
        level:
          type: integer
        guild_code:
          type: string
    CharacterResponse:
      type: object
      required:
        - name
        - server
        - class
        - level
        - dungeon_success
        - guild_id
        - id
      properties:
        id:
          type: string
        name:
          type: string
        server:
          type: string
        class:
          type: string
        level:
          type: integer
        guild_id:
          type: string
        dungeon_success:
          type: array
          items:
            type: string
    SearchResponse:
      type: object
      required:
        - character_name
        - character_id
        - discord_name
        - class
        - level
        - missing_success
        - guild_id
        - guild_name
      properties:
        character_name:
          type: string
        character_id:
          type: string
        discord_name:
          type: string
        class:
          type: string
        level:
          type: integer
        guild_id:
          type: string
        guild_name:
          type: string
        missing_success:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        error:
          type: string


