openapi: 3.0.0
info:
  title: Characters
  description: Characters
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /characters:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CharacterInfo'
      security:
        - basicAuth: []
      responses:
        '201':
          description: Guild created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      description: Get the owned characters of the user
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Character owned by the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CharacterResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Token Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer
  schemas:
    CharacterInfo:
      type: object
      required:
        - name
        - server
        - class
        - level
        - guild_code
      properties:
        name:
          type: string
        server:
          type: string
        class:
          type: string
        level:
          type: integer
        guild_code:
          type: string
    CharacterResponse:
      type: object
      required:
        - name
        - server
        - class
        - level
        - achievements
        - guild_id
      properties:
        name:
          type: string
        server:
          type: string
        class:
          type: string
        level:
          type: integer
        guild_id:
          type: string
        achievements:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        error:
          type: string


